- hosts: controller
  tasks:
    - name: create local.sh
      become: yes
      blockinfile:
        path: /opt/stack/devstack/local.sh
        create: True
        mode: 0777
        block: |
          # This policy is default to admin only in glance. Override
          # here to allow everyone and every type of image (private
          # or public) to copy. This way we will be able to test copy
          # image via non-admin as well as on private images.
          echo $'{"copy_image": ""}' > /etc/glance/policy.json
